repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.0.1'
  hooks:
  - id: check-merge-conflict
    exclude: "rst$"
- repo: https://github.com/asottile/yesqa
  rev: v1.2.3
  hooks:
  - id: yesqa
- repo: https://github.com/pre-commit/mirrors-isort
  rev: 'v5.9.3'
  hooks:
  - id: isort
- repo: https://github.com/psf/black
  rev: '21.8b0'
  hooks:
  - id: black
    language_version: python3   # Should be a command that runs python3.6+
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.0.1'
  hooks:
  - id: check-case-conflict
  - id: check-json
  - id: check-xml
  - id: debug-statements
  - id: check-added-large-files
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: trailing-whitespace
  - id: check-symlinks
  - id: debug-statements
- repo: https://github.com/asottile/pyupgrade
  rev: 'v2.25.1'
  hooks:
  - id: pyupgrade
    args: ['--py36-plus']
- repo: https://gitlab.com/pycqa/flake8
  rev: '3.9.2'
  hooks:
  - id: flake8
    exclude: "^docs/"
- repo: https://github.com/rhysd/actionlint
  rev: v1.6.3
  hooks:
  - id: actionlint-docker
    args:
    - -ignore
    - 'SC2155:'
    - -ignore
    - 'SC2086:'
    - -ignore
    - 'SC1004:'
ci:
  skip:
  - actionlint-docker
