name: 'Upload Coverage'
description: 'Uploade coverage file for later composing'
inputs:
  file:
    description: 'Coverage file name'
    required: false
    default: '.coverage'
  artifact:
    description: 'The artifact name to store coverage chunk'
    required: false
    default: 'coverage'
runs:
  using: "composite"
  steps:
    - name: Calculate target file name
      id: meta
      run: |
        import os, secrets
        rnd = secrets.token_hex(16)
        with open(os.environ["GITHUB_OUTPUT"], "a") as f:
          print(f"file=.coverage.{rnd}", file=f)
      shell: python
    - name: Rename file
      run: mv ${{ inputs.file }} ${{ steps.meta.outputs.file }}
      shell: bash
    - name: Upload coverage artifact
      uses: actions/upload-artifact@v4.4.0
      with:
        name: ${{ inputs.artifact }}
        path: ${{ steps.meta.outputs.file }}
        if-no-files-found: error
        retention-days: 1
        include-hidden-files: true
