name: 'Upload Coverage'
description: 'Uploade coverage file for later composing'
inputs:
  key:
    description: 'key info for coverage file, e.g. py39-linux'
    required: true
  file:
    description: 'Coverage file name'
    required: false
    default: './coverage.xml'
  artifact:
    description: 'The artifact name to store coverage chunk'
    required: false
    default: 'coverage'
runs:
  using: "composite"
  steps:
    - name: Calculate target file name
      id: meta
      run: echo "::set-output name=file::coverage-${{ inputs.key }}.xml"
      shell: bash
    - name: Rename file
      run: mv ${{ inputs.file }} ${{ steps.meta.outputs.file }}
      shell: bash
    - name: Upload coverage artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: ${{ inputs.artifact }}
        path: ${{ steps.meta.outputs.file }}
        if-no-files-found: error
        retention-days: 1
