name: Enable auto-merge
on:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]'}}
    steps:
      - name: metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for bot PRs
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  pre-commit-bot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'pre-commit-ci[bot]' }}
    steps:
      - name: Enable auto-merge for bot PRs
        run: |
          gh pr merge --auto --squash "$PR_URL"
          gh pr edit --add-label 'dependencies' "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  other:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' &&
            contains(github.event.pull_request.labels.*.name, 'dependencies') }}
    steps:
      - name: Enable auto-merge for bot PRs
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
